### PR TITLE
remove direct subscribe/unsubscribe

### PR DESCRIPTION
**Pull request by vitaliystoliarovcc**
Asana ticket: https://app.asana.com/0/1125859137800433/1200259339573685

Since only "trades" was used in the subscription, the subscribe/unsubscribe feature was completely removed

### CODE REVIEW

**Review by avsek477 — APPROVED** [review]
lgtm

**Review by tarcisiozf — APPROVED** [review]
lgtm

**Review by robertkowalski — APPROVED** [review]
lgtm, will merge after HF release on Wed

**Comment by robertkowalski** [comment]
frontend still subscribes, is currently cleaned up:

```
  bfx:hf:server:exchange-clients:bitfinex subscribing to channel 
["trades" {"exchange":"bitfinex","lev":3.33,"quote":"TESTUSD","base":"TESTBTC","
wsID":"tTESTBTC:TESTUSD","restID":"tTESTBTC:TESTUSD","
uiID":"TESTBTC/TESTUSD","contexts":["e","m"],"p":1}] +5s
  ```

**Pull request merged**
